### ISSUE TITLE
Could you provide how to setup CTS Verifier AS project? 

### ISSUE THREAD

**Issue by samlin001** [Alwin-Lin/development-debug-androidTest#2]
It'll be useful to be explore CTS Verifier source in AS IDE & Attach Debugger to Android process.
Ref: https://source.android.com/compatibility/cts/verifier

Thanks.

**Comment by Alwin-Lin** [comment]
Fixed.
https://github.com/Alwin-Lin/development-debug-androidTest/tree/master/ctsVerifier
